---
- name: Configuring Apache
  hosts: all
  tasks:
  - name: Install the package
    yum:
     name: httpd
     state: present

  - name: creating index file
    template:
     src: mycode.j2
     dest: /var/www/html/index.html

  - name: starting the service
    service:
     name: httpd
     state: started
