---
- name: Configuring Web Server
  hosts: all
  tasks:
  - name: Installing the package
    yum:
     name: httpd
     state: present
  - name: Creating The Content
    copy:
     content: "Hello From Ansible Tower"
     dest: /var/www/html/index.html

  - name: Starting the Service
    service:
     name: httpd
     state: started
     enabled: true
